# Generated by Django 6.0.1 on 2026-04-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('banner_type', models.CharField(choices=[('top', 'Top Banner'), ('bottom1', 'Bottom Banner 1'), ('bottom2', 'Bottom Banner 2'), ('bottom3', 'Bottom Banner 3')], default='top', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jewelry/')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
