# Generated by Django 6.0.1 on 2026-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jewelry_images/'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
