# Generated by Django 6.0.1 on 2026-02-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_jewelry_category_alter_jewelry_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('top', 'Top Banner'), ('bottom1', 'Bottom Banner 1'), ('bottom2', 'Bottom Banner 2'), ('bottom3', 'Bottom Banner 3')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
