# Generated by Django 6.0.1 on 2026-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('top', 'Top Banner'), ('bottom1', 'Bottom Banner 1'), ('bottom2', 'Bottom Banner 2'), ('bottom3', 'Bottom Banner 3')], default='top', max_length=20),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
